import type { Metadata } from 'next'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service | RepsReceipts',
  description: 'RepsReceipts terms of service. Read the terms and conditions governing your use of our receipt generation platform.',
  alternates: { canonical: '/terms' },
  robots: { index: true, follow: true },
}

export default function Terms() {
  return (
    <>
      <main style={{ minHeight: '100vh', background: '#fff' }}>
        <Header />

        <section style={{ maxWidth: 740, margin: '0 auto', padding: '60px 20px' }}>
          <h1 style={{ fontSize: 'clamp(1.8rem, 3vw, 2.4rem)', fontWeight: 700, color: '#111', marginBottom: 8 }}>
            Terms of Service
          </h1>
          <p style={{ color: '#888', fontSize: '0.85rem', marginBottom: 40 }}>Last updated: June 2026</p>

          <div style={{ color: '#444', lineHeight: 1.8, fontSize: '1rem' }}>
            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#111', marginTop: 32, marginBottom: 8 }}>1. Acceptance of Terms</h2>
            <p>By accessing or using RepsReceipts ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#111', marginTop: 32, marginBottom: 8 }}>2. Description of Service</h2>
            <p>RepsReceipts provides a web-based receipt template generation tool that allows users to create formatted receipt documents based on brand templates. The Service is intended for personal documentation, creative, and educational purposes.</p>

            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#111', marginTop: 32, marginBottom: 8 }}>3. Acceptable Use</h2>
            <p>You agree to use the Service only for lawful purposes. You must not use receipts generated by RepsReceipts to:</p>
            <ul style={{ paddingLeft: 24, marginBottom: 16 }}>
              <li>Commit fraud, deception, or misrepresentation.</li>
              <li>Make false insurance claims.</li>
              <li>Deceive any individual, company, or authority.</li>
              <li>Violate any applicable law or regulation.</li>
            </ul>
            <p>You are solely responsible for how you use generated receipts. RepsReceipts accepts no liability for misuse.</p>

            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#111', marginTop: 32, marginBottom: 8 }}>4. Accounts and Subscriptions</h2>
            <p>To access certain features, you must create an account. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account. Subscription fees are billed in advance and are non-refundable except as described in our Refund Policy.</p>

            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#111', marginTop: 32, marginBottom: 8 }}>5. Intellectual Property</h2>
            <p>All content on RepsReceipts — including templates, code, design, and text — is the property of RepsReceipts or its licensors. You may not reproduce, distribute, or create derivative works without express written permission. Brand names and logos referenced in templates are the property of their respective owners. RepsReceipts is not affiliated with, endorsed by, or connected to any of these brands.</p>

            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#111', marginTop: 32, marginBottom: 8 }}>6. Disclaimer of Warranties</h2>
            <p>The Service is provided "as is" without warranties of any kind, either express or implied. RepsReceipts does not warrant that the Service will be uninterrupted, error-free, or that generated documents will be accurate or suitable for any particular purpose.</p>

            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#111', marginTop: 32, marginBottom: 8 }}>7. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, RepsReceipts shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service.</p>

            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#111', marginTop: 32, marginBottom: 8 }}>8. Termination</h2>
            <p>We reserve the right to suspend or terminate your account at any time if we determine that you have violated these Terms. Upon termination, your right to use the Service will cease immediately.</p>

            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#111', marginTop: 32, marginBottom: 8 }}>9. Changes to Terms</h2>
            <p>We may update these Terms from time to time. Continued use of the Service after changes are posted constitutes acceptance of the updated Terms.</p>

            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#111', marginTop: 32, marginBottom: 8 }}>10. Contact</h2>
            <p>For questions about these Terms, contact us at <strong>support@repsreceipt.com</strong>.</p>
          </div>

          <div style={{ marginTop: 48, display: 'flex', gap: 16, flexWrap: 'wrap' }}>
            <Link href="/privacy" style={{ color: '#5462ea', fontSize: '0.9rem' }}>Privacy Policy</Link>
            <Link href="/refund" style={{ color: '#5462ea', fontSize: '0.9rem' }}>Refund Policy</Link>
          </div>
        </section>

        <Footer />
      </main>
    </>
  )
}
